name: deploy

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup 
        uses: actions/checkout@v3

      - name: python
        uses: actions/python@v4
        with:
          python-version: '3.9'

      - name: req
        run: pip instal -r reqirments.txt

      - name: run
        run: python src/app.py


    

          
